### ISSUE TITLE
Import of brain failing on several OSs

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/Brion#197]
Since a couple of days, my jenkins plans are failing with the error below.

This happens on Ubuntu 16.04 (default python 2.7) and CSCS viz (redhat software collections python 2.7). It also happens when I manually try to run on my CSCS viz account.

Traceback (most recent call last):
  File "/home/bbprelman/workspace/sim.bglibpy/os/Ubuntu-16.04/BGLibPy/.tox/py27/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bbprelman/workspace/sim.bglibpy/os/Ubuntu-16.04/BGLibPy/bglibpy/tests/test_ssim.py", line 229, in test_compare_traces
    voltage_bglib = self.ssim_bglib.get_mainsim_voltage_trace(gid=1)
  File "/home/bbprelman/workspace/sim.bglibpy/os/Ubuntu-16.04/BGLibPy/bglibpy/ssim.py", line 794, in get_mainsim_voltage_trace
    voltage = self.bc_simulation.report('soma').get_gid(gid).values
  File "/home/bbprelman/workspace/sim.bglibpy/os/Ubuntu-16.04/BGLibPy/.tox/py27/local/lib/python2.7/site-packages/bluepy/v2/simulation.py", line 124, in report
    result = report_type(report_path)
  File "/home/bbprelman/workspace/sim.bglibpy/os/Ubuntu-16.04/BGLibPy/.tox/py27/local/lib/python2.7/site-packages/bluepy/v2/impl/compartment_report.py", line 189, in __init__
    import brain
  File "/home/bbprelman/workspace/sim.bglibpy/os/Ubuntu-16.04/BGLibPy/.tox/py27/local/lib/python2.7/site-packages/brain/__init__.py", line 24, in <module>
    from ._brain import *
ImportError: /home/bbprelman/workspace/sim.bglibpy/os/Ubuntu-16.04/BGLibPy/.tox/py27/local/lib/python2.7/site-packages/brain/_brain.so: undefined symbol: BZ2_bzDecompress

**Comment by hernando** [comment]
I have a guess for the reason, but I need you to confirm that you are using the Python wheel from our devpi.

**Comment by wvangeit** [comment]
Yep, this a brain install pulled in by bluepy from our devpi

**Comment by wvangeit** [comment]
Btw, how can I can link the devpi versions to the github releases ? 
I only see 2.0.0 as latest release on github, although devpi has 3.0.0 (for Brain at least, I assume that version number is the same as Brion) ?
Which is the last version that still works ?

**Comment by hernando** [comment]
We have not made an official release yet for 3.0.0 in Github. The wheel in our devpi is in the dev channel, we have not released any stable version in the release channel, but I'll take note of it and do it once I fix the wheel to avoid this problem in the future.

**Comment by wvangeit** [comment]
Ok, I've pinned to version of Brain to 2.1.0 for now in BGLibPy so that users are not affected.

**Comment by hernando** [comment]
I think we have found the reason, I hope to get the wheel updated tomorrow.

**Comment by hernando** [comment]
The Python wheel has been fixed, tested and deployed on devpi.

**Comment by wvangeit** [comment]
Btw, could you maybe bump up the version number slightly when you upload a new version of the devpi package ? That way I can force the installation of the new version from dependent packages.

**Comment by hernando** [comment]
This is something we discussed internally and decided not to do for the dev channel for the moment, but should definitely do it for the release channel. We opted for not doing it to avoid the complexity of the version handling in the scripts generating the wheel, but we may reconsider this decision and maybe add a devX tag to the packages in dev,
